# Generated by Django 4.2.10 on 2024-03-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_group_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заголовок'),
        ),
    ]
